# Generated by Django 5.1.4 on 2025-02-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklistAPI', '0002_category_alter_bookdb_options_bookdb_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookdb',
            options={'ordering': ['-created_on']},
        ),
    ]
